
# ========================================数据集===================================
DataSet:
  prefix: ./CatDog/ # 数据集根路径 /home/IMG_PATH/ 
  category: {"cat":0,"dog":1}
  batch: 64
 
# ========================================模型===================================
Models: 
  backbone: resnest50d
  checkpoint: None
  