
# ========================================数据集===================================
DataSet:
  prefix: /dataset/lipengbo/ViolenceClass/V2/ # 数据集根路径
  category: {"normal":0,"fire":1,"guns":2,"knife":3,"blood":4}
 



# # others
# batch_size: 120
# net:
#   name: ResNeSt
#   pretrain: /code/lipengbo/ViolenceClass/checkpoint/exp1/ResNeSt/ResNeSt_099.pth