# ========================================数据集===================================
DataSet:
  prefix: ./CatDog/    # 数据集根路径 /home/IMG_PATH/ 
  size: [224,224]     # 训练尺寸
  category: {"cat":0,"dog":1}  # 类别
  ratio: 0.9  # train:val比例  
  sampler: "balance" # 支持['normal','balance']    balance:类别平衡采样(每轮重采样)
  batch: 8
# ========================================模型===================================
Models: 
  backbone: mynet # 主干网络  优先级：自定义 > timm库
  loss: cross_entropy  # 损失函数  支持['cross_entropy','focal_loss']
  optimizer: SGD       # 优化器    支持['SGD','Adam']

# ========================================训练===================================
Train:
  lr: 0.001
  epochs: 100 
  milestones: [70,90] #学习率衰减
