# ========================================数据集===================================
DataSet:
  prefix: /home/IMG_PATH/  # 数据集根路径
  ratio: 0.9 # train:val比例
  category: {"cat":0,"dog":1}
  sampler: "balance" # normal:正常   balance:类别平衡采样(每轮重新采样)
  batch: 32
# ========================================模型===================================
Models: 
  backbone: resnest50d #主干网络  优先级: timm模型>本地模型
  head: cross_entropy # 损失函数  支持['cross_entropy','focal_loss']
  optimizer: SGD  # 优化器  支持['SGD','SAM']

# ========================================训练===================================
Train:
  lr: 0.001
  epochs: 100 
  milestones: [70,90] #学习率衰减
