name: Verification 
on: push
jobs:
  build:
    runs-on: ubuntu-latest # 虚拟环境
    steps:
    - name: Checkout codes # 获取源码
      uses: actions/checkout@main
    - name: Installation depends # 安装依赖
      run: | 
        cd Classification
        pip install -r ./Package/requirements.txt   &&   pip install ./Package/*zip
        echo Hello, Classification!